[project]
name = "learning-buddy"
version = "0.1.0"
description = "An application that helps you learn and retain knowledge."
readme = "README.md"
authors = [
    { name = "Ana Jurjevic", email = "jurjevic.anaa@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
learning-buddy = "learning_buddy:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.8",
]

[tool.mypy]
python_version = "3.12"
strict = true

[tool.pytest.ini_options]
testpaths=["tests"]
